name = "rox-deep-dive-proxy"
main = "src/index.js"
compatibility_date = "2026-08-27"
account_id = "97e53ca181262b222f79bb27f0aef9aa"

[[kv_namespaces]]
binding = "ROX_ROUTING"
id = "b5084162327642029f73ecbae632e1bb"

[[kv_namespaces]]
binding = "ROX_EVENTS"
id = "99a868b608a5490f9f00de524c733497"
